name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django-notes-app
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django-notes-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker images with docker-compose
        run: docker compose -p custom -f docker-compose.yml build

      - name: Tag images for Docker Hub
        run: |
          docker tag custom_django:latest "${{ secrets.DOCKERHUB_USERNAME }}/django_cont:latest"
          docker tag custom_nginx:latest "${{ secrets.DOCKERHUB_USERNAME }}/nginx_cont:latest"

      - name: Push images to Docker Hub
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/django_cont:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/nginx_cont:latest"
