name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node-express-mongodb

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # removed cache to avoid lock file error

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test
  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CI-CD-Pipeline-tutorial

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/node-express-mongodb:latest" .

      - name: Push Docker image to Docker Hub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/node-express-mongodb:latest"   
